# Julia Workshop, Control Flow

## Loops 

In [1]:
#=
1. While Loops
2. For Loops 
=#

In [2]:
#while loops
n = 0
while n < 10
    n+= 1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [4]:
names = ["Ted", "Rob", "Barney", "Lily"]
i = 1 
while i<= length(names)
    name = names[i]
    println("Hi, my name is $name")
    i += 1
end

Hi, my name is Ted
Hi, my name is Rob
Hi, my name is Barney
Hi, my name is Lily


In [5]:
for n in 1:10 
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [6]:
names = ["Ted", "Rob", "Barney", "Lily"]
for name in names
    println("Hi, my name is $name")
end

Hi, my name is Ted
Hi, my name is Rob
Hi, my name is Barney
Hi, my name is Lily


In [7]:
for n = 1:10 
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [13]:
m, n = 5, 5
a= zeros(m,n)

5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [15]:
for i in 1:m
    for j in 1:n 
        a[i,j] = i + j
    end 
end 
a
        

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [16]:
b = zeros((m,n))

5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [17]:
for i in 1:m, j in 1:n
    b[i,j]= i +j 
end 
b

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [20]:
# more "julia" way to create addition table, didnt need to pre initial the matrix 
c = [i + j for i in 1:m, j in 1:n]

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [22]:
for n in 1:10 
    a = [i + j for i in 1:n , j in 1:n ]
    display(a)
end

1×1 Matrix{Int64}:
 2

2×2 Matrix{Int64}:
 2  3
 3  4

3×3 Matrix{Int64}:
 2  3  4
 3  4  5
 4  5  6

4×4 Matrix{Int64}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Matrix{Int64}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Matrix{Int64}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Matrix{Int64}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

9×9 Matrix{Int64}:
  2   3   4   5   6   7   8   9  10
  3   4   5   6   7   8   9  10  11
  4   5   6   7   8   9  10  11  12
  5   6   7   8   9  10  11  12  13
  6   7   8   9  10  11  12  13  14
  7   8   9  10  11  12  13  14  15
  8   9  10  11  12  13  14  15  16
  9  10  11  12  13  14  15  16  17
 10  11  12  13  14  15  16  17  18

10×10 Matrix{Int64}:
  2   3   4   5   6   7   8   9  10  11
  3   4   5   6   7   8   9  10  11  12
  4   5   6   7   8   9  10  11  12  13
  5   6   7   8   9  10  11  12  13  14
  6   7   8   9  10  11  12  13  14  15
  7   8   9  10  11  12  13  14  15  16
  8   9  10  11  12  13  14  15  16  17
  9  10  11  12  13  14  15  16  17  18
 10  11  12  13  14  15  16  17  18  19
 11  12  13  14  15  16  17  18  19  20

## Conditionals

In [23]:
#= 
if cond1
    option1 
elseif 
    cond2
else 
    cond3
end
=#

In [24]:
x = 10
y = 5

5

In [26]:
if x > y
    println("$x is larger than $y")
elseif y > x
    println("$y is larger than $x")
else 
    println("$x and $y are equal")
end

10 is larger than 5


In [29]:
if x > y 
    x 
else 
    y 
end 

10

In [31]:
#= 
a ? b : c 
if a 
    b
else 
    c
end 
=#

In [28]:
(x > y) ? x : y

10

In [32]:
#a && b 

LoadError: TypeError: non-boolean (Matrix{Int64}) used in boolean context

In [33]:
(x>y) && println("$x is larger than $y")
(x< y) && println("$y is larger than $x")

10 is larger than 5


false

## Functions 

In [34]:
function sayhi(name)
    println("Hi $name, how are you?")
end 

sayhi (generic function with 1 method)

In [35]:
function f(x)
    x^2
end

f (generic function with 1 method)

In [36]:
sayhi("Carolina")

Hi Carolian, how are you?


In [37]:
f(4)

16

In [41]:
sayhi(name) = print("Hi $name, how are you?")

sayhi (generic function with 1 method)

In [42]:
sayhi("Mary")

Hi Mary, how are you?

In [45]:
hello = name -> println("Hi $name, its great to see you!")

#9 (generic function with 1 method)

In [46]:
f3 = x -> x^2

#11 (generic function with 1 method)

In [48]:
hello("Caro")

Hi Caro, its great to see you!


In [49]:
f3(6)

36

## Duck Typing in Julia 

In [50]:
sayhi(3243224)

Hi 3243224, how are you?

In [51]:
a = rand(3,3)

3×3 Matrix{Float64}:
 0.708259  0.428387  0.207797
 0.865846  0.183984  0.0749384
 0.850326  0.997695  0.0501011

In [52]:
f(a)

3×3 Matrix{Float64}:
 1.04924   0.589543  0.189688
 0.836267  0.479533  0.197462
 1.5087    0.597814  0.253971

In [53]:
v = rand(3)

3-element Vector{Float64}:
 0.32166174091608335
 0.16482304932204017
 0.132806418238418

In [55]:
f(v)

LoadError: MethodError: no method matching ^(::Vector{Float64}, ::Int64)
Closest candidates are:
  ^(::Union{AbstractChar, AbstractString}, ::Integer) at strings/basic.jl:730
  ^(::Complex{<:AbstractFloat}, ::Integer) at complex.jl:860
  ^(::Complex{<:Integer}, ::Integer) at complex.jl:862
  ...

## Mutating v Non Mutating Functions

In [56]:
v = [3,5,2]

3-element Vector{Int64}:
 3
 5
 2

In [57]:
sort(v)

3-element Vector{Int64}:
 2
 3
 5

In [58]:
v

3-element Vector{Int64}:
 3
 5
 2

In [59]:
sort!(v)

3-element Vector{Int64}:
 2
 3
 5

In [60]:
v

3-element Vector{Int64}:
 2
 3
 5

## Broadcasting

In [61]:
A = [i + 3*j for j in 0:2, i in 1:3]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [62]:
f(A)

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

In [63]:
f.(A)

3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81

In [64]:
A[2,2]

5

In [65]:
A[2,2]^2

25

In [67]:
b[2,2]

4.0

In [68]:
v = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [69]:
f.(v)

3-element Vector{Int64}:
 1
 4
 9